name: Check Pull Request Metadata
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
jobs:
  check-pr-title:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write # conventional-commits-pr-action: PR comments
    steps:
      - name: Check pull request title
        uses: jef/conventional-commits-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: true # Post a comment in the pull request conversation with examples.
